config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :pay_methods
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pay_method.rb
class PayMethod < ApplicationRecord
  belongs_to :payable, polymorphic: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :product
  belongs_to :pay_method
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pay_methods_controller.rb
class PayMethodsController < ApplicationController
  before_action :set_pay_method, only: [:show, :edit, :update, :destroy]

  # GET /pay_methods
  # GET /pay_methods.json
  def index
    @pay_methods = PayMethod.all
  end

  # GET /pay_methods/1
  # GET /pay_methods/1.json
  def show
  end

  # GET /pay_methods/new
  def new
    @pay_method = PayMethod.new
  end

  # GET /pay_methods/1/edit
  def edit
  end

  # POST /pay_methods
  # POST /pay_methods.json
  def create
    @pay_method = PayMethod.new(pay_method_params)

    respond_to do |format|
      if @pay_method.save
        format.html { redirect_to @pay_method, notice: 'Pay method was successfully created.' }
        format.json { render :show, status: :created, location: @pay_method }
      else
        format.html { render :new }
        format.json { render json: @pay_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pay_methods/1
  # PATCH/PUT /pay_methods/1.json
  def update
    respond_to do |format|
      if @pay_method.update(pay_method_params)
        format.html { redirect_to @pay_method, notice: 'Pay method was successfully updated.' }
        format.json { render :show, status: :ok, location: @pay_method }
      else
        format.html { render :edit }
        format.json { render json: @pay_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pay_methods/1
  # DELETE /pay_methods/1.json
  def destroy
    @pay_method.destroy
    respond_to do |format|
      format.html { redirect_to pay_methods_url, notice: 'Pay method was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pay_method
      @pay_method = PayMethod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pay_method_params
      params.require(:pay_method).permit(:payable_id, :payable_type)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:success, :product_id, :pay_method_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pay_methods_helper.rb
module PayMethodsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PolyEcommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pay_methods/_form.html.erb
<%= form_with(model: pay_method, local: true) do |form| %>
  <% if pay_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pay_method.errors.count, "error") %> prohibited this pay_method from being saved:</h2>

      <ul>
      <% pay_method.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :payable_id %>
    <%= form.text_field :payable_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pay_methods/edit.html.erb
<h1>Editing Pay Method</h1>

<%= render 'form', pay_method: @pay_method %>

<%= link_to 'Show', @pay_method %> |
<%= link_to 'Back', pay_methods_path %>

app/views/pay_methods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pay Methods</h1>

<table>
  <thead>
    <tr>
      <th>Payable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pay_methods.each do |pay_method| %>
      <tr>
        <td><%= pay_method.payable %></td>
        <td><%= link_to 'Show', pay_method %></td>
        <td><%= link_to 'Edit', edit_pay_method_path(pay_method) %></td>
        <td><%= link_to 'Destroy', pay_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pay Method', new_pay_method_path %>

app/views/pay_methods/new.html.erb
<h1>New Pay Method</h1>

<%= render 'form', pay_method: @pay_method %>

<%= link_to 'Back', pay_methods_path %>

app/views/pay_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payable:</strong>
  <%= @pay_method.payable %>
</p>

<%= link_to 'Edit', edit_pay_method_path(@pay_method) %> |
<%= link_to 'Back', pay_methods_path %>

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :success %>
    <%= form.check_box :success %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :pay_method_id %>
    <%= form.text_field :pay_method_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Success</th>
      <th>Product</th>
      <th>Pay method</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.success %></td>
        <td><%= payment.product %></td>
        <td><%= payment.pay_method %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Success:</strong>
  <%= @payment.success %>
</p>

<p>
  <strong>Product:</strong>
  <%= @payment.product %>
</p>

<p>
  <strong>Pay method:</strong>
  <%= @payment.pay_method %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>